### PR TITLE
Troubleshooting

### PR DESCRIPTION
**Pull request by drwasho**
Added a troubleshooting guide for a bug some users may encounter on OSX.

### CODE REVIEW

**Comment by richardschneider** [comment]
This looks like a line ending issue in the `ob` script.  I'd rather fix the script, than tell user's what todo.

**Comment by richardschneider** [comment]
Could you try the new release, 0.0.47, on OSX.  Hopefully it likes a LF in the script.  Sorry to ask this, but I don't have access to an OSX machine (too expensive).

**Comment by drwasho** [comment]
Yep, seems to work just fine!

**Comment by richardschneider** [comment]
Thanks for the testing.

**Pull request closed without merging**
